# Generated by Django 3.1.7 on 2022-05-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='car',
            field=models.CharField(default='Honda', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='engine',
            field=models.CharField(default='1.9 Lt', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default='Fit', max_length=255),
        ),
    ]
