# Generated by Django 3.1.7 on 2022-05-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220505_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='car',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='engine',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=255),
        ),
    ]
