# Generated by Django 3.1.7 on 2022-05-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='model',
            field=models.CharField(default='', max_length=255),
        ),
    ]
