# Generated by Django 3.1.7 on 2022-05-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='engine',
            field=models.CharField(default='', max_length=255),
        ),
    ]
