# Generated by Django 3.1.7 on 2022-05-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_engine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='car',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='model',
        ),
    ]
